[package]
name = "spy-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
nng = "1.0.1"
<<<<<<< HEAD
<<<<<<< HEAD
tui = "0.19"
crossterm = "0.25"
shared = { version = "0.1.0", path = "../../shared" }
<<<<<<< HEAD
dashmap = "6.1.0"
chrono = "0.4.38"
=======
>>>>>>> 269499f (add: spy-detector(main.rs))
=======
shared = { path = "../../shared" }
>>>>>>> 07118aa (update: cargo.toml)
=======
simple_logger = "5.0.0"
log = "0.4.22"
<<<<<<< HEAD
>>>>>>> 6285823 (upated with simple logger)
=======
screen-13 = "0.11.4"
<<<<<<< HEAD
>>>>>>> bf971f9 (add: time constraint)
=======
dashmap = "6.1.0"
>>>>>>> 6b10299 (added loop for matching individual inv messages)
