[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }
tungstenite = "0.24.0"
serde_json = "1.0.133"

[features]
# Treat warnings as a build error.
strict = []
