[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }
tokio-tungstenite = "0.27.0"
serde_json = "1.0.142"

[features]
# Treat warnings as a build error.
strict = []
