[workspace]

resolver = "2"
members = [
  "shared",
  "extractors/ebpf",
  "extractors/rpc",
  "extractors/p2p",
  "tools/logger",
  "tools/websocket",
  "tools/metrics",
  "tools/connectivity-check",
]
