# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import p2p_pb2 as p2p__pb2
import connection_pb2 as connection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwrapper.proto\x12\x07wrapper\x1a\tp2p.proto\x1a\x10\x63onnection.proto\"[\n\x07Wrapper\x12\x1b\n\x03msg\x18\x01 \x01(\x0b\x32\x0c.p2p.MessageH\x00\x12+\n\x04\x63onn\x18\x02 \x01(\x0b\x32\x1b.connection.ConnectionEventH\x00\x42\x06\n\x04wrap')



_WRAPPER = DESCRIPTOR.message_types_by_name['Wrapper']
Wrapper = _reflection.GeneratedProtocolMessageType('Wrapper', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPER,
  '__module__' : 'wrapper_pb2'
  # @@protoc_insertion_point(class_scope:wrapper.Wrapper)
  })
_sym_db.RegisterMessage(Wrapper)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRAPPER._serialized_start=55
  _WRAPPER._serialized_end=146
# @@protoc_insertion_point(module_scope)
