{
 "title": "addr message service bits",
 "tags": [
  "addr",
  "big-playlist"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "service bits",
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "| value | bit | name                  |\n|-------|-----|-----------------------|\n| 1     | 0   | NODE_NETWORK          |\n| 4     | 2   | NODE_BLOOM            |\n| 8     | 3   | NODE_WITNESS         |\n| 64    | 6   | NODE_COMPACT_FILTERS |\n| 1024  | 10  | NODE_NETWORK_LIMITED |\n| 2048  | 11  | NODE_P2P_V2           |\n"
   }
  },
  {
   "title": "inbound addr address service bits",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_addr_services_bits_bucket{direction=\"inbound\"}[1m])",
     "legendFormat": "{{le}} bit"
    }
   ]
  },
  {
   "title": "inbound addrv2 address service bits",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_addrv2_services_bits_bucket{direction=\"inbound\"}[1m])",
     "legendFormat": "{{le}} bit"
    }
   ]
  },
  {
   "title": "outbound addr address service bits",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 10, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "delta(peerobserver_p2p_addr_services_bits_bucket{direction=\"outbound\"}[1m])",
     "legendFormat": "{{le}} bit"
    }
   ]
  },
  {
   "title": "outbound addrv2 address service bits",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_addrv2_services_bits_bucket{direction=\"outbound\"}[1m])",
     "legendFormat": "{{le}} bit"
    }
   ]
  }
 ]
}