{
 "title": "[mempool] mempool size (tx count, vbytes, memory usage)",
 "tags": [
  "mempool",
  "big-playlist"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "mempool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bitcoin_mempool_usage", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "mempool transaction size (size of transactions in mempool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bitcoin_mempool_bytes", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "mempool transaction count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bitcoin_mempool_size", "legendFormat": "{{host}}" }
   ]
  }
 ]
}