{
 "title": "[mempool] mempool memory usage",
 "tags": [
  "mempool",
  "big-playlist"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "mempool fullness (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "peerobserver_rpc_mempoolinfo_memory_usage / peerobserver_rpc_mempoolinfo_memory_max",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "peerobserver_rpc_mempoolinfo_memory_usage",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "mempool transaction vsize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "peerobserver_rpc_mempoolinfo_transaction_vbyte",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "mempool memory usage bytes per vbyte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "peerobserver_rpc_mempoolinfo_memory_usage / peerobserver_rpc_mempoolinfo_transaction_vbyte",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}