[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }

prometheus = "0.13.0"
lazy_static = "1.5.0"

[features]
# Treat warnings as a build error.
strict = []
