[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }

prost = "0.10"
nng = "1.0.1"
libbpf-rs = { version = "0.20.1" }
libc = "0.2"

[build-dependencies]
libbpf-cargo = { version = "0.20.1" }

[features]
# Treat warnings as a build error.
strict = []
