{
 "title": "addr message timestamp offset",
 "tags": [ "addr" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "connection_direction", "query": { "query": "label_values(direction)" } }
  ]
 },
 "panels": [
  {
   "title": "$connection_direction addr message timestamp offsets (past)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "repeat": "connection_direction",
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_addr_timestamp_offset_seconds_bucket{timestamp_offset=\"past\", direction=\"$connection_direction\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$connection_direction addr message timestamp offsets (future)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "repeat": "connection_direction",
   "targets": [
    {
     "expr": "delta(networkobserver_p2p_addr_timestamp_offset_seconds_bucket{timestamp_offset=\"future\", direction=\"$connection_direction\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$connection_direction addrv2 message timestamp offsets (past)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_addrv2_timestamp_offset_seconds_bucket{timestamp_offset=\"past\", direction=\"$connection_direction\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$connection_direction addrv2 message timestamp offsets (future)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "delta(networkobserver_p2p_addrv2_timestamp_offset_seconds_bucket{timestamp_offset=\"future\", direction=\"$connection_direction\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}