{
 "title": "Connections",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Connections from 209.222.252.0/24",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound_address{addr=~\"(209.222.252.*)\"}[1m])",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Connections from 162.218.65.0/24",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound_address{addr=~\"(162.218.65.*)\"}[1m])",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "currrent connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "networkobserver_conn_outbound_current",
     "legendFormat": "outbund"
    },
    {
     "expr": "networkobserver_conn_inbound_current",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(idelta(networkobserver_conn_outbound[1m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound[1m])",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "subnets with more than 5 connections per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound_subnet{subnet!~\"(^\\\\[.*\\\\]$)\"}[1m]) > 5",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "4 or more inbound connections by IP in 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound_address[1m]) > 10",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Evicted connections per minute ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_evicted[1m])",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Inbound by network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound_network[1m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "delta(networkobserver_conn_closed[1m])",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "Misbehaving",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "networkobserver_conn_misbehaving"
    }
   ]
  },
  {
   "title": "Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_closed_network[1m])",
     "legendFormat": "network {{network}}"
    }
   ]
  },
  {
   "title": ">3 connections by subnet in the last hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(networkobserver_conn_inbound_subnet{subnet!~\"(^\\\\[.*\\\\]$)\"}[60m]) > 3",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "3 or more connections by this netgroup in the last hour",
   "type": "stat",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(networkobserver_conn_inbound_netgroup[60m]) > 2.5",
     "legendFormat": "{{netgroup}}"
    }
   ]
  },
  {
   "title": "Misbehaving",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(networkobserver_conn_misbehaving_score_increase) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Misbehaving",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(networkobserver_conn_misbehaving) by (missbehavingmessage)",
     "legendFormat": "{{missbehavingmessage}}"
    }
   ]
  },
  {
   "title": "Misbehaving",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(networkobserver_conn_misbehaving) by (missbehavingmessage)",
     "legendFormat": "{{missbehavingmessage}}"
    }
   ]
  }
 ]
}