{
 "title": "Feefilter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "inbound feerates in feefilter msgs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "networkobserver_p2p_feefilter_feerate{direction=\"inbound\"}",
     "legendFormat": "{{feerate}} sat / kvbyte"
    }
   ]
  },
  {
   "title": "inbound",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_feefilter_feerate{direction=\"inbound\"}[1m])",
     "legendFormat": "{{direction}} {{feerate}}sat/kvB"
    }
   ]
  },
  {
   "title": "outbound",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_feefilter_feerate{direction=\"outbound\"}[1m])",
     "legendFormat": "{{direction}} {{feerate}}sat/kvB"
    }
   ]
  }
 ]
}