{
 "title": "Pings",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pings per minute (>5)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_ping_address[1m]) > 5",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "more than 10 pings in the last minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_ping_address[1m]) > 10 ",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "More than 300 pings in 4h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(networkobserver_p2p_ping_address[4h]) > 300",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "idelta(networkobserver_p2p_ping_address[1m]) > 0",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Inbound pings per second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(idelta(networkobserver_p2p_message_count{message=\"ping\", direction=\"inbound\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pings per minute (>5)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "irate(networkobserver_p2p_ping_address{addr=\"35.215.2.174\"}[60s]) > 5",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Inbound pings per second per connected peer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(delta(networkobserver_p2p_message_count{message=\"ping\", direction=\"inbound\"}[1m])) / on() group_right() (networkobserver_conn_inbound_current + networkobserver_conn_outbound_current)"
    },
    {}
   ]
  }
 ]
}