{
 "title": "addresses per addr message",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "outbound addr message entries",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "delta(peerobserver_p2p_addr_addresses_bucket{direction=\"outbound\"}[1m]) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "inbound addr message entries",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(peerobserver_p2p_addr_addresses_bucket{direction=\"inbound\"}[1m]) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "outbound addrv2 message entries",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "delta(peerobserver_p2p_addrv2_addresses_bucket{direction=\"outbound\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "inbound addrv2 message entries",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "delta(peerobserver_p2p_addrv2_addresses_bucket{direction=\"inbound\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}