{
 "title": "Connections",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "currrent connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_conn_outbound_current",
     "legendFormat": "outbund"
    },
    {
     "expr": "peerobserver_conn_inbound_current",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(idelta(peerobserver_conn_outbound[1m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_inbound[1m])",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "subnets with more than 5 connections per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_inbound_subnet{subnet!~\"(^\\\\[.*\\\\]$)\"}[1m]) > 5",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "4 or more inbound connections by IP in 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_inbound_address[1m]) > 10",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Evicted connections per minute ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_evicted[1m])",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Inbound by network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_inbound_network[1m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_closed[1m])",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "Misbehaving connections",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "last_over_time(peerobserver_conn_misbehaving[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_closed_network[1m])",
     "legendFormat": "network {{network}}"
    }
   ]
  },
  {
   "title": ">3 connections by subnet in the last hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_inbound_subnet{subnet!~\"(^\\\\[.*\\\\]$)\"}[60m]) > 3",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "3 or more connections by this netgroup in the last hour",
   "type": "stat",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(peerobserver_conn_inbound_netgroup[60m]) > 2.5",
     "legendFormat": "{{netgroup}}"
    }
   ]
  },
  {
   "title": "Misbehaving",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(peerobserver_conn_misbehaving) by (missbehavingmessage)",
     "legendFormat": "{{missbehavingmessage}}"
    }
   ]
  }
 ]
}