{
 "title": "INVs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "inbound inv entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "idelta(peerobserver_p2p_inv_entries{direction=\"inbound\"}[1m])",
     "legendFormat": "{{inv_type}}"
    }
   ]
  },
  {
   "title": "outbound inv entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "idelta(peerobserver_p2p_inv_entries{direction=\"outbound\"}[1m])",
     "legendFormat": "{{inv_type}}"
    }
   ]
  },
  {
   "title": "homogeneous invvs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(peerobserver_p2p_invs_homogeneous[1m])",
     "legendFormat": "homogeneous {{direction}}"
    },
    {}
   ]
  },
  {
   "title": "heterogeneous INVs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peerobserver_p2p_invs_heterogeneous",
     "legendFormat": "heterogeneous {{direction}}"
    }
   ]
  },
  {
   "title": "entries per inbound inv",
   "type": "heatmap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_inv_entries_histogram_bucket{direction=\"inbound\"}[3m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "entries per outbound inv",
   "type": "heatmap",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_inv_entries_histogram_bucket{direction=\"outbound\"}[3m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}