{
 "title": "Mempool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "added per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(peerobserver_mempool_added[1m]) / 60",
     "legendFormat": "added"
    }
   ]
  },
  {
   "title": "vbyte added per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(peerobserver_mempool_added_vbytes[1m]) / 60",
     "legendFormat": "vbyte added"
    }
   ]
  },
  {
   "title": "replaced per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(peerobserver_mempool_replaced[1m])",
     "legendFormat": "replaced"
    }
   ]
  },
  {
   "title": "vbyte replaced per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(peerobserver_mempool_replaced_vbytes[1m])",
     "legendFormat": "vbyte replaced"
    }
   ]
  },
  {
   "title": "rejections by reason",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(peerobserver_mempool_rejected[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}