{
 "title": "Reject",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "non-\"tx\" rejects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "networkobserver_p2p_reject_addr{rejectcommand!=\"tx\"}",
     "legendFormat": "{{rejectcommand}} {{addr}}"
    }
   ]
  },
  {
   "title": "Rejects by addr",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(networkobserver_p2p_reject_addr) by (addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "rejected \"tx\" messages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(networkobserver_p2p_reject_addr{rejectcommand=\"tx\"}) by (rejectreason)",
     "legendFormat": "{{rejectreason}}"
    }
   ]
  },
  {
   "title": "who rejected what how often for being \"invalid\"",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "networkobserver_p2p_reject_addr{rejectreason=\"Invalid\"}",
     "legendFormat": "{{addr}} rejected {{rejectcommand}}"
    }
   ]
  },
  {
   "title": "who rejected what how often for being \"NonStandard\"",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "networkobserver_p2p_reject_addr{rejectreason=\"NonStandard\"}",
     "legendFormat": "{{addr}} rejected {{rejectcommand}}"
    }
   ]
  },
  {
   "title": "reject info",
   "type": "stat",
   "gridPos": { "h": 64, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "networkobserver_p2p_reject_message",
     "legendFormat": "{{rejectcommand}} - reason={{rejectreason}} - message={{rejectmessage}}"
    }
   ]
  }
 ]
}