# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addrman.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddrman.proto\x12\x07\x61\x64\x64rman\"a\n\x0c\x41\x64\x64rmanEvent\x12!\n\x03new\x18\x01 \x01(\x0b\x32\x12.addrman.InsertNewH\x00\x12%\n\x05tried\x18\x02 \x01(\x0b\x32\x14.addrman.InsertTriedH\x00\x42\x07\n\x05\x65vent\"\x83\x01\n\tInsertNew\x12\x10\n\x08inserted\x18\x01 \x02(\x08\x12\x0e\n\x06\x62ucket\x18\x02 \x02(\x05\x12\x12\n\nbucket_pos\x18\x03 \x02(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x02(\t\x12\x0f\n\x07\x61\x64\x64r_AS\x18\x05 \x02(\r\x12\x0e\n\x06source\x18\x06 \x02(\t\x12\x11\n\tsource_AS\x18\x07 \x02(\r\"s\n\x0bInsertTried\x12\x0e\n\x06\x62ucket\x18\x01 \x02(\x05\x12\x12\n\nbucket_pos\x18\x02 \x02(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x64\x64r_AS\x18\x04 \x02(\r\x12\x0e\n\x06source\x18\x05 \x02(\t\x12\x11\n\tsource_AS\x18\x06 \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addrman_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDRMANEVENT']._serialized_start=26
  _globals['_ADDRMANEVENT']._serialized_end=123
  _globals['_INSERTNEW']._serialized_start=126
  _globals['_INSERTNEW']._serialized_end=257
  _globals['_INSERTTRIED']._serialized_start=259
  _globals['_INSERTTRIED']._serialized_end=374
# @@protoc_insertion_point(module_scope)
