# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import net_msg_pb2 as net__msg__pb2
import net_conn_pb2 as net__conn__pb2
import addrman_pb2 as addrman__pb2
import mempool_pb2 as mempool__pb2
import validation_pb2 as validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65vent_msg.proto\x12\tevent_msg\x1a\rnet_msg.proto\x1a\x0enet_conn.proto\x1a\raddrman.proto\x1a\rmempool.proto\x1a\x10validation.proto\"\x9a\x02\n\x08\x45ventMsg\x12\x11\n\ttimestamp\x18\n \x02(\x04\x12\x1f\n\x17timestamp_subsec_micros\x18\x0b \x02(\r\x12\x1f\n\x03msg\x18\x01 \x01(\x0b\x32\x10.net_msg.MessageH\x00\x12)\n\x04\x63onn\x18\x02 \x01(\x0b\x32\x19.net_conn.ConnectionEventH\x00\x12(\n\x07\x61\x64\x64rman\x18\x03 \x01(\x0b\x32\x15.addrman.AddrmanEventH\x00\x12(\n\x07mempool\x18\x04 \x01(\x0b\x32\x15.mempool.MempoolEventH\x00\x12\x31\n\nvalidation\x18\x05 \x01(\x0b\x32\x1b.validation.ValidationEventH\x00\x42\x07\n\x05\x65vent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EVENTMSG']._serialized_start=110
  _globals['_EVENTMSG']._serialized_end=392
# @@protoc_insertion_point(module_scope)
