# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: net_conn.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'net_conn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import primitive_pb2 as primitive__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enet_conn.proto\x12\x08net_conn\x1a\x0fprimitive.proto\"\xa1\x02\n\x0f\x43onnectionEvent\x12,\n\x06\x63losed\x18\x01 \x01(\x0b\x32\x1a.net_conn.ClosedConnectionH\x00\x12=\n\x0finbound_evicted\x18\x02 \x01(\x0b\x32\".net_conn.EvictedInboundConnectionH\x00\x12.\n\x07inbound\x18\x03 \x01(\x0b\x32\x1b.net_conn.InboundConnectionH\x00\x12\x30\n\x08outbound\x18\x04 \x01(\x0b\x32\x1c.net_conn.OutboundConnectionH\x00\x12\x36\n\x0bmisbehaving\x18\x05 \x01(\x0b\x32\x1f.net_conn.MisbehavingConnectionH\x00\x42\x07\n\x05\x65vent\"d\n\nConnection\x12\x0f\n\x07peer_id\x18\x01 \x02(\x04\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x02(\t\x12&\n\tconn_type\x18\x03 \x02(\x0e\x32\x13.primitive.ConnType\x12\x0f\n\x07network\x18\x04 \x02(\r\"P\n\x10\x43losedConnection\x12\"\n\x04\x63onn\x18\x01 \x02(\x0b\x32\x14.net_conn.Connection\x12\x18\n\x10time_established\x18\x02 \x02(\x04\"X\n\x18\x45victedInboundConnection\x12\"\n\x04\x63onn\x18\x01 \x02(\x0b\x32\x14.net_conn.Connection\x12\x18\n\x10time_established\x18\x02 \x02(\x04\"U\n\x11InboundConnection\x12\"\n\x04\x63onn\x18\x01 \x02(\x0b\x32\x14.net_conn.Connection\x12\x1c\n\x14\x65xisting_connections\x18\x02 \x02(\x04\"V\n\x12OutboundConnection\x12\"\n\x04\x63onn\x18\x01 \x02(\x0b\x32\x14.net_conn.Connection\x12\x1c\n\x14\x65xisting_connections\x18\x02 \x02(\x04\"4\n\x15MisbehavingConnection\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x0f\n\x07message\x18\x02 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'net_conn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTIONEVENT']._serialized_start=46
  _globals['_CONNECTIONEVENT']._serialized_end=335
  _globals['_CONNECTION']._serialized_start=337
  _globals['_CONNECTION']._serialized_end=437
  _globals['_CLOSEDCONNECTION']._serialized_start=439
  _globals['_CLOSEDCONNECTION']._serialized_end=519
  _globals['_EVICTEDINBOUNDCONNECTION']._serialized_start=521
  _globals['_EVICTEDINBOUNDCONNECTION']._serialized_end=609
  _globals['_INBOUNDCONNECTION']._serialized_start=611
  _globals['_INBOUNDCONNECTION']._serialized_end=696
  _globals['_OUTBOUNDCONNECTION']._serialized_start=698
  _globals['_OUTBOUNDCONNECTION']._serialized_end=784
  _globals['_MISBEHAVINGCONNECTION']._serialized_start=786
  _globals['_MISBEHAVINGCONNECTION']._serialized_end=838
# @@protoc_insertion_point(module_scope)
