# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p_extractor.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'p2p_extractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13p2p_extractor.proto\x12\rp2p_extractor\"R\n\x11P2PExtractorEvent\x12\x34\n\rping_duration\x18\x01 \x01(\x0b\x32\x1b.p2p_extractor.PingDurationH\x00\x42\x07\n\x05\x65vent\" \n\x0cPingDuration\x12\x10\n\x08\x64uration\x18\x01 \x02(\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_extractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_P2PEXTRACTOREVENT']._serialized_start=38
  _globals['_P2PEXTRACTOREVENT']._serialized_end=120
  _globals['_PINGDURATION']._serialized_start=122
  _globals['_PINGDURATION']._serialized_end=154
# @@protoc_insertion_point(module_scope)
