# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprimitive.proto\x12\tprimitive\"7\n\x0bTransaction\x12\x0c\n\x04txid\x18\x01 \x02(\x0c\x12\r\n\x05wtxid\x18\x02 \x02(\x0c\x12\x0b\n\x03raw\x18\x03 \x01(\x0c\"\x84\x01\n\x0b\x42lockHeader\x12\x0f\n\x07version\x18\x01 \x02(\x11\x12\x16\n\x0eprev_blockhash\x18\x02 \x02(\x0c\x12\x13\n\x0bmerkle_root\x18\x03 \x02(\x0c\x12\x0c\n\x04time\x18\x04 \x02(\r\x12\x0c\n\x04\x62its\x18\x05 \x02(\r\x12\r\n\x05nonce\x18\x06 \x02(\r\x12\x0c\n\x04hash\x18\x07 \x02(\x0c\"\xd7\x01\n\x07\x41\x64\x64ress\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\x0e\n\x04ipv4\x18\x02 \x01(\tH\x00\x12\x0e\n\x04ipv6\x18\x03 \x01(\tH\x00\x12\x0f\n\x05torv2\x18\x04 \x01(\tH\x00\x12\x0f\n\x05torv3\x18\x05 \x01(\tH\x00\x12\r\n\x03i2p\x18\x06 \x01(\tH\x00\x12\x0f\n\x05\x63jdns\x18\x07 \x01(\tH\x00\x12,\n\x07unknown\x18\x08 \x01(\x0b\x32\x19.primitive.UnknownAddressH\x00\x12\x10\n\x08services\x18\t \x02(\x04\x12\x0c\n\x04port\x18\n \x02(\rB\t\n\x07\x61\x64\x64ress\"-\n\x0eUnknownAddress\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\x0c\"\xdb\x01\n\rInventoryItem\x12\x15\n\x0btransaction\x18\x01 \x01(\x0cH\x00\x12\x0f\n\x05\x62lock\x18\x02 \x01(\x0cH\x00\x12\r\n\x03wtx\x18\x03 \x01(\x0cH\x00\x12\x1d\n\x13witness_transaction\x18\x04 \x01(\x0cH\x00\x12\x17\n\rwitness_block\x18\x05 \x01(\x0cH\x00\x12\x17\n\rcompact_block\x18\x06 \x01(\x0cH\x00\x12)\n\x07unknown\x18\x07 \x01(\x0b\x32\x16.primitive.UnknownItemH\x00\x12\x0f\n\x05\x65rror\x18\x0f \x01(\x08H\x00\x42\x06\n\x04item\"-\n\x0bUnknownItem\x12\x10\n\x08inv_type\x18\x01 \x02(\r\x12\x0c\n\x04hash\x18\x02 \x02(\x0c\"N\n\x14PrefilledTransaction\x12\x12\n\ndiff_index\x18\x01 \x02(\r\x12\"\n\x02tx\x18\x02 \x02(\x0b\x32\x16.primitive.Transaction*[\n\x08\x43onnType\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Inbound\x10\x01\x12\x15\n\x11OutboundFullRelay\x10\x02\x12\x12\n\x0e\x42lockRelayOnly\x10\x03\x12\n\n\x06\x46\x65\x65ler\x10\x04')

_CONNTYPE = DESCRIPTOR.enum_types_by_name['ConnType']
ConnType = enum_type_wrapper.EnumTypeWrapper(_CONNTYPE)
Unknown = 0
Inbound = 1
OutboundFullRelay = 2
BlockRelayOnly = 3
Feeler = 4


_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_BLOCKHEADER = DESCRIPTOR.message_types_by_name['BlockHeader']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_UNKNOWNADDRESS = DESCRIPTOR.message_types_by_name['UnknownAddress']
_INVENTORYITEM = DESCRIPTOR.message_types_by_name['InventoryItem']
_UNKNOWNITEM = DESCRIPTOR.message_types_by_name['UnknownItem']
_PREFILLEDTRANSACTION = DESCRIPTOR.message_types_by_name['PrefilledTransaction']
Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

BlockHeader = _reflection.GeneratedProtocolMessageType('BlockHeader', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKHEADER,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.BlockHeader)
  })
_sym_db.RegisterMessage(BlockHeader)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.Address)
  })
_sym_db.RegisterMessage(Address)

UnknownAddress = _reflection.GeneratedProtocolMessageType('UnknownAddress', (_message.Message,), {
  'DESCRIPTOR' : _UNKNOWNADDRESS,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.UnknownAddress)
  })
_sym_db.RegisterMessage(UnknownAddress)

InventoryItem = _reflection.GeneratedProtocolMessageType('InventoryItem', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYITEM,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.InventoryItem)
  })
_sym_db.RegisterMessage(InventoryItem)

UnknownItem = _reflection.GeneratedProtocolMessageType('UnknownItem', (_message.Message,), {
  'DESCRIPTOR' : _UNKNOWNITEM,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.UnknownItem)
  })
_sym_db.RegisterMessage(UnknownItem)

PrefilledTransaction = _reflection.GeneratedProtocolMessageType('PrefilledTransaction', (_message.Message,), {
  'DESCRIPTOR' : _PREFILLEDTRANSACTION,
  '__module__' : 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:primitive.PrefilledTransaction)
  })
_sym_db.RegisterMessage(PrefilledTransaction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNTYPE._serialized_start=836
  _CONNTYPE._serialized_end=927
  _TRANSACTION._serialized_start=30
  _TRANSACTION._serialized_end=85
  _BLOCKHEADER._serialized_start=88
  _BLOCKHEADER._serialized_end=220
  _ADDRESS._serialized_start=223
  _ADDRESS._serialized_end=438
  _UNKNOWNADDRESS._serialized_start=440
  _UNKNOWNADDRESS._serialized_end=485
  _INVENTORYITEM._serialized_start=488
  _INVENTORYITEM._serialized_end=707
  _UNKNOWNITEM._serialized_start=709
  _UNKNOWNITEM._serialized_end=754
  _PREFILLEDTRANSACTION._serialized_start=756
  _PREFILLEDTRANSACTION._serialized_end=834
# @@protoc_insertion_point(module_scope)
