# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: validation.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'validation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10validation.proto\x12\nvalidation\"Q\n\x0fValidationEvent\x12\x35\n\x0f\x62lock_connected\x18\x01 \x01(\x0b\x32\x1a.validation.BlockConnectedH\x00\x42\x07\n\x05\x65vent\"}\n\x0e\x42lockConnected\x12\x0c\n\x04hash\x18\x01 \x02(\x0c\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\x14\n\x0ctransactions\x18\x03 \x02(\x03\x12\x0e\n\x06inputs\x18\x04 \x02(\x05\x12\x0e\n\x06sigops\x18\x05 \x02(\x03\x12\x17\n\x0f\x63onnection_time\x18\x06 \x02(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'validation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATIONEVENT']._serialized_start=32
  _globals['_VALIDATIONEVENT']._serialized_end=113
  _globals['_BLOCKCONNECTED']._serialized_start=115
  _globals['_BLOCKCONNECTED']._serialized_end=240
# @@protoc_insertion_point(module_scope)
