[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }

prost = "0.10"
nng = "1.0.1"

[features]
# Treat warnings as a build error.
strict = []
