name: build (ubuntu)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependecies
      run: |
        sudo apt update -y
        sudo apt-get install -y \
          protobuf-compiler \
          libelf-dev \
          clang \
          llvm \
          llvm-14 \
          zstd \
          binutils-dev \
          elfutils \
          gcc-multilib
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
