[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

prometheus = "0.13.0"
lazy_static = "1.4.0"

log = "0.4.14"
simple_logger = "1.9.0"

prost = "0.10"
nng = "1.0.1"
